### ISSUE TITLE
HAProxy Service support

### ISSUE THREAD

**Issue by thegrumpylion** [jaredhendrickson13/pfsense-api#10]
Hi, thanks for this attempt to automate pfsense.

Do you plan on adding more services and is HAProxy one of them?

Is it possible to write a small guide on how we can contribute new services to this project?

Cheers,
Nik.

**Comment by jaredhendrickson13** [comment]
Hi there,

Thanks for your interest in this project. The plan is to focus primarily on pfSense's core services before adding support for add-on packages. HAProxy being one of the firsts I plan to do. 

Community contributions are welcome and very much needed. Since this project is starting to get more interest, I am currently working on a contributors guide for anyone who wishes to develop their own custom API endpoints or contribute to the primary project here. I should have that published by the end of the week. 

Let me know if you have any other questions or if there is any way I can help.

Thanks!

**Comment by thegrumpylion** [comment]
Very nice! Looking forward to the guide.

**Comment by jaredhendrickson13** [comment]
Hi again,

Sorry for the wait. I have just released v0.0.3 of the API today. This release includes the contributor guide in the docs directory. This release also includes a simple framework for contributors to use when developing additional API calls. Hopefully this make things easier to get started. 

Feel free to reach out to me directly with any questions. I will close this issue for now. 

Thanks!

**Comment by qkrtjddlsgh** [comment]
Hi. Thank you for your hard work on pfsense.

Do you have any plans to provide APIs for Haproxy Service in pfsense 2.5 or higher?
I can make settings for Haproxy in the pfsense UI, but I would like to automate it like any other core feature of pfsense.

Thanks.

**Comment by slobberbone** [comment]
Thanks for your work on this project !
I'm interested by the ability to manage haproxy too ...
