### ISSUE TITLE
Update Unbound Host Override throws error "Invalid unbound host override IP address" when sending multiple ip-addresses

### ISSUE THREAD

**Issue by mschneider94** [jaredhendrickson13/pfsense-api#105]
API-Call Update Unbound Host Override throws error "Invalid unbound host override IP address" when sending multiple ip-addresses as suggested in pfSense-webConfigurator

IPv4 or IPv6 comma-separated addresses to be returned for the host
e.g.: 192.168.100.100 or fd00:abcd::
or list 192.168.1.3,192.168.4.5,fc00:123::3

Workaround:
Create individual Host-Overrides per IP-Address, all with the same host- and domain-name.

-----------------------------
pfSense-pkg-API-1.1_7
Name           : pfSense-pkg-API
Version        : 1.1_7
Installed on   : Mon Mar 15 20:48:21 2021 CET
Origin         : sysutils/pfSense-pkg-API
Architecture   : FreeBSD:12:amd64
Prefix         : /usr/local
Categories     : sysutils
Licenses       : APACHE20
Maintainer     : jaredhendrickson13@gmail.com
WWW            : https://github.com/jaredhendrickson13/pfsense-api
Comment        : pfSense API package
Annotations    :
        FreeBSD_version: 1200086
Flat size      : 1.65MiB

**Comment by jaredhendrickson13** [comment]
Hey!

Thanks for reporting this. This is actually expected behavior at the moment. This was briefly mentioned in #73, but the comma separated values for host overrides is a new feature in pfSense 2.5 that is not allowed in pfSense 2.4. To keep things backwards compatible and avoid cluttering the codebase with version specific conditions, I have held off on implementing pfSense 2.5 specific features for now. As you mentioned, you are able to create one IPv4 and one IPv6 host override with the same host/domain combination which is supported in both pfSense 2.4 and pfSense 2.5.

That being said, v1.2.0 of the API should be released within the next week which will be last release supporting pfSense 2.4 (excluding patches of course). I will then start planning for the v1.3.0 release and will be sure to add this one to the project board. 

Thanks!
