### ISSUE TITLE
pfsense+

### ISSUE THREAD

**Issue by philippenc** [jaredhendrickson13/pfsense-api#140]
hello, i don't know if this is the right place to ask this question but, is the api pfsense + compatible?
 thank you

**Comment by jaredhendrickson13** [comment]
Hey! 

Unfortunately it is not compatible with pfSense Plus. At the moment there are some core differences between pfSense CE and pfSense Plus that prevent the API package from installing and operating properly. Since pfSense Plus is closed-source it is much more difficult to develop and support the package for that platform. Given the scope of Netgate's new development structure, I would expect pfSense Plus to contain it's own API in the near future. 

Thanks!

**Comment by VIKMSTR** [comment]
Just a quick note to this:
By a coincidence, I've managed to put my hands on the NETGATE device running the pfsense+ in version 21.05.2-RELEASE. 
Basically I just created new override file with copying just a piece of code from the API to system.inc .
Then I had to rebuild it for the ARM architecture, cause the device is running on ARM64 chipset. 
Installed, restarted GUI and ...it worked!

There are some new features and the network interfaces looks like they are handled bit differently, but for the basic stuff it 
should be working. 

However, no warranty, and especially no warranty for the future, since the development of + and ce versions is supposed to be separate.
