### ISSUE TITLE
Filter rule association when creating NAT Port forward

### ISSUE THREAD

**Issue by hisakiyo** [jaredhendrickson13/pfsense-api#148]
Hi,

Is it possible to set "Filter rule association" parameter to "new" when creating new NAT Port forward ?
https://github.com/jaredhendrickson13/pfsense-api#1-create-nat-port-forwards

Cheers

**Comment by jaredhendrickson13** [comment]
Hey!

Currently the API hard sets the `associated-rule-id` field to `pass` and does not allow other options. This is primarily due to the complexity of the dependency chain that is required when manipulating port forwards with linked firewall rules. That being said, I'll keep this open as a feature request for future enhancement. Seems this information should also be added to the documentation in a future release. 

Thanks!

**Comment by Harryols** [comment]
I have done made it, how can I add the code?
