### ISSUE TITLE
WireGuard package support

### ISSUE THREAD

**Issue by Hoto-Cocoa** [jaredhendrickson13/pfsense-api#158]
How about supporting WireGuard?

**Comment by MrDoudou** [comment]
I would need this feature very badly. Would it be possible to finance its development to have it quickly? We strongly need it for our hosting startup.

**Comment by jaredhendrickson13** [comment]
I've been getting a lot of requests for this one recently. There's a bit of work that needs to be done to the framework before this can be implemented cleanly in a production release, but I will try to have this included in the next release v1.4.0 given the demand. I'll update the issue was progress is made. 

@MrDoudou Feel free to send me an email with the workflow you are needing and I'll see what I can do to help. My email address is listed on my profile. I don't ask for any direct compensation but you can sponsor the project if you feel inclined.

**Comment by austin1howard** [comment]
hey @jaredhendrickson13 sorry for a bit of a necro here but curious if this has ever been prioritized?

**Comment by jaredhendrickson13** [comment]
@austin1howard There were prototype models and endpoints built for Wireguard a while back, but the way the pfSense functions for Wireguard are written made it difficult to fit into the existing API framework so they never made it into a release. That being said, Wireguard and a couple other packages will be built as v2 endpoints. If things go as planned, v2 should be released this spring. You should start to see dev builds for v2 in the next few weeks, but they may not include the Wireguard endpoints until early next year. I'll update this issue once there is movement on those endpoints.

**Comment by jaredhendrickson13** [comment]
WireGuard tunnels, peers and settings endpoints are available in the latest dev build of v2: https://github.com/jaredhendrickson13/pfsense-api/releases/tag/v2.0.0-dev-094eefe
