### ISSUE TITLE
SSH update malfunctions if no settings are defined

### ISSUE THREAD

**Issue by oakslabs** [jaredhendrickson13/pfsense-api#180]
**Describe the bug**
On a new pfSense with no SSH settings, the PUT call to the /api/v1/services/sshd endpoint returns a 200 status code but the configuration doesn't change (and the return data is "2"). Once the SSH configuration exists on the pfSense the call works correctly, the configuration updates, and the configuration data is returned.

**To Reproduce**
1. Create a new pfSense
2. Authenticate, and send the following request:

$ssh_body = '{
    "sshdkeyonly":  "enabled",
    "enable":  true,
    "port":  2222
}'

Invoke-RestMethod -Method Put -Uri "https://$hostname/api/v1/services/sshd" -Body $ssh_body -Headers $header

3. See the successful reply, but no change in the configuration:

status  : ok
code    : 200
return  : 0
message : Success
data    : 2

4. Manually enable SSH.
5. Repeat step 2.
6. See the successful reply, the configuration information, and the changes in the GUI:

status  : ok
code    : 200
return  : 0
message : Success
data    : @{enable=enabled; sshdkeyonly=enabled; port=2222}

**Expected behavior**
The API ideally would be able to create an SSH configuration from scratch. Otherwise, an error message would be ideal.

**pfSense Version & Package Version:**
 - pfSense Version: 2.5.2-RELEASE (amd64)
 - Package Version 1.3.2

**Affected Endpoints:**
 - URL: /api/v1/services/sshd

**Comment by jaredhendrickson13** [comment]
Hey!

I can't seem to reproduce this. Here's my process. From a brand new install of pfSense 2.5.2 with no additional changes besides setting up the WAN interface, I install the latest version of the API via console (without manually enabling SSH). I then run the following API call (I don't use PowerShell, but here is the curl equivalent):

```
curl -s -k -d '{"client-id": "admin", "client-token": "pfsense", "enable": true, "sshdkeyonly": "enabled", "port": 2222}' -X PUT https://172.16.209.178/api/v1/services/sshd
```
I get the following response:
```json
{
    "status":"ok",
    "code":200,
    "return":0,
    "message":"Success",
    "data": {
        "enable":"enabled",
        "sshdkeyonly":"enabled",
        "port":"2222"
    }
}
```

After this I use nmap to verify that the custom SSH port is open:
```
$ nmap -Pn 172.16.209.178 -p 2222
Host discovery disabled (-Pn). All addresses will be marked 'up' and scan times will be slower.
Starting Nmap 7.91 ( https://nmap.org ) at 2021-12-18 08:15 MST
Nmap scan report for 172.16.209.178
Host is up (0.054s latency).

PORT     STATE SERVICE
2222/tcp open  EtherNetIP-1

Nmap done: 1 IP address (1 host up) scanned in 0.19 seconds
```
Then I try to actually SSH to the port, where I see the service is running on the port but I get a public key denied since I have not added my SSH key to the admin user. Which is expected:
```
$ ssh admin@172.16.209.178 -p 2222
The authenticity of host '[172.16.209.178]:2222 ([172.16.209.178]:2222)' can't be established.
ED25519 key fingerprint is SHA256:SCRUBBED.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[172.16.209.178]:2222' (ED25519) to the list of known hosts.
admin@172.16.209.178: Permission denied (publickey).
```

My assumption is something is happening to your request body before the API request is received, perhaps something PowerShell is doing. To see the data as it's received by the API, you can manually add `var_dump($this->initial_data);` to the first line of the `validate_payload()` method within /etc/inc/api/models/APIServices/APIServicesSSHdUpdate.inc. This will print the request data received by the API and might better explain why you're experiencing this. Be sure to remove that line once you are done.

Thanks!

**Comment by oakslabs** [comment]
Hey Jared!

I've seen the PS misbehave in other areas, so although I never circled back to testing this, I believe you are correct. I'll close out this issue for now -- thanks for the tips on the additional diagnostics!
