### ISSUE TITLE
401 client error Unauthorized on call through python requests

### ISSUE THREAD

**Issue by yaleman** [jaredhendrickson13/pfsense-api#194]
I'm trying to test creating an alias, using python requests. I'm using local auth and getting 401 Unauthorized on POST calls, but can auth using GET requests.

**To Reproduce**

Not working:
``` python
import requests
url = "https://example.com/api/v1/firewall/alias"
payload = {
    "name": "zzz_bogus",
    "type": "host",
    "descr": "Bogus description",
    "address": "bogus.lol",
    "detail": "bogus.lol is bogus",
    "client-id": "<username>",
    "client-token": "<password>"
}
response = requests.post(url, json=payload)
response.raise_for_status()
```

Works fine:
``` python
import requests
url = "https://example.com/api/v1/firewall/alias"
payload = {
    "client-id": "<username>",
    "client-token": "<password>"
}
response = requests.post(url, json=payload)
response.raise_for_status()
```

**Expected behavior**

A `200` response.

**Screenshots or Response**
Response data ( 
```
print(response.text)
> {"status":"unauthorized","code":401,"return":3,"message":"Authentication failed","data":[]}
```

**pfSense Version & Package Version:**
 - pfSense Version: 2.5.2-RELEASE (amd64) 
 - Package Version: v1.3.3

**Affected Endpoints:**
 - URL:/api/v1/firewall/alias

**Additional context**

**Comment by yaleman** [comment]
Then again I just got a 405 trying to do a `PUT` so I'm wondering if nginx is being a jerk and I've missed something?

```
405 Client Error: Not Allowed for url: https://example.com:8443/api/v1/system/api
```
body of response:
```
b'<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n'
```

**Comment by yaleman** [comment]
Worked it out - looks like I'd gotten banned by pfsense - had this as a single IP (my nagios box) - updated to include my subnet and everything's working currently.


<img width="1124" alt="Screen Shot 2022-01-24 at 21 39 58" src="https://user-images.githubusercontent.com/168188/150776591-b373058d-973c-4cca-865b-4823b56bc9e0.png">

**Comment by jaredhendrickson13** [comment]
Hey!

That 405 response you received when making a PUT request typically indicates the webConfigurator was not restarted as required after the API was installed. This can easily be missed if the entire install command was copied. pfSense's default nginx configuration does not allow PUT or DELETE requests so the API installs an nginx configuration override to allow those methods, but the override is only applied when the webConfigurator is restarted. In this case, the system_advanced_admin.php page where the Login Protection settings are actually triggers a webConfigurator restart whenever the save button is pressed, so the login protection changes likely weren't what corrected the issue here. 

Hope this helps explain the behavior a little better. Sounds like you've got things working so I'll close this out in the meantime, but feel free to reopen if this problem persists. 

Thanks!
