### ISSUE TITLE
missing endpoints

### ISSUE THREAD

**Issue by ozrouter** [jaredhendrickson13/pfsense-api#20]
this shows as an endpoint:
`/api/v1/firewall/rule/`
this doesn't:
`/api/v1/firewall/rules/`
(404 error)
The doc's show 'rules' though...

also `/api/v1/firewall/rule/add` is missing

any idea why?

**Comment by jaredhendrickson13** [comment]
Hey there,

Looks like you may be looking at the documentation for the beta releases (v0.0.1-v0.0.3). Since the initial v1.0.0 release, the endpoint has been `/api/v1/firewall/rule` and alternate HTTP methods were made possible to support a more REST like API architecture. POST requests to this endpoint will create a new firewall rule, GET requests read existing rules, PUT requests will update an existing firewall rule and DELETE requests will delete an existing firewall rule.

You can view the v1.0.1+ documentation at https://github.com/jaredhendrickson13/pfsense-api#firewallrule or at URI`/api/documentation/`of your pfSense instance.

**Comment by ozrouter** [comment]
hey, great plugin mate!

yeah i was using both docs as the latest didn't quite show me how to create the curl URL. I can now update firewall rules, cheers

**Comment by jaredhendrickson13** [comment]
Glad to hear. I'm hoping to bring back the HTTP client examples in the documentation in the near future. Feel free to let me know if you run into any other troubles. 

Thanks!
