### ISSUE TITLE
Parallel firewall rule creations succeed in API but missing in pfSense

### ISSUE THREAD

**Issue by jared-gs** [jaredhendrickson13/pfsense-api#238]
**Describe the bug**
When rules are added in parallel (i.e. multiple POST to `/api/v1/firewall/rule` simultaneously), API will return `Status 200` for each request, but not all rules get created in pfSense. 

**To Reproduce**
This can be reproduced using this example code that creates 5-firewall rules in parallel:

https://gist.github.com/jared-gs/abca3e028a5bda351cead755f6e5bd63#file-main-go

`$ go run main.go`

**Expected behavior**
All rules created with API and return `200` should exist. API should return non-200 for rules that fail to create or don't exist.

**Screenshots or Response**
Reproduction command output (all API requests succeed):

```
2022/05/29 13:16:38 created firewall rule
2022/05/29 13:16:38 created firewall rule
2022/05/29 13:16:38 created firewall rule
2022/05/29 13:16:38 created firewall rule
2022/05/29 13:16:38 created firewall rule

Process finished with the exit code 0
```

Console output (only one rule exists):

![image](https://user-images.githubusercontent.com/4740273/170883702-853486a0-c249-4650-804a-5987e4ba9e40.png)

**pfSense Version & Package Version:**
 - pfSense Version: 2.6.0-RELEASE
 - Package Version 1.4.2

**Affected Endpoints:**
 - URL: `/api/v1/firewall/rule` (perhaps other endpoints also affected)

**Additional context**
If the API is overloaded, then likely sane throttling defaults are the way forward.

**Comment by jaredhendrickson13** [comment]
Hey!

This would be expected behavior. There are a couple problems with making simultaneous API calls:

1) To put simply, pfSense does not handle simultaneous writes at the rate of which API enables you to have. This was a limitation identified and tested very early in development of this API and is mentioned in the API documentation [here](https://github.com/jaredhendrickson13/pfsense-api#limitations). Technically, the API calls did succeed but pfSense's `write_config()` and/or `parse_config()` function overwrote them due to the speed of which they occurred. There is not a consistent or universal way to address this without changing the native pfSense code. Several API endpoints call native pfSense functions that would not respect any solution implemented to the API alone. The client is expected to delay API calls to prevent conflicts. 

2) There is a another problem specific to firewall rules. pfSense assigns a unique ID to each firewall rule created referred to as the tracking ID. This ID is simply a unix timestamp of the moment the firewall rule was created. Since these timestamps only increment with each second passed, you are essentially limited to creating one firewall rule per second on pfSense. 

There is one option to do this though, PUT requests to /api/v1/firewall/rule/flush will allow you to replace all firewall rules with a specified set of rules. This is possible since replacing all existing rules will allow for retroactively creating the tracker IDs without possible conflicts with existing rules. However, the endpoint should be considered experimental since the tracker may no longer match the created time of the firewall rule. This does not cause any apparent issues, but is largely untested as it is a process that does not exist on pfSense natively. 

Thanks!

**Comment by jared-gs** [comment]
Thanks for that explanation, I had overlooked that limitation in the documentation. Going forward, I'll look for ways to prevent simultaneous writes.
