### ISSUE TITLE
Issue : API install for pfSense plus (arm64)

### ISSUE THREAD

**Issue by Augustin987** [jaredhendrickson13/pfsense-api#239]
**Describe the bug**
When i try to install pfSense API for pfSense plus v22.01 on arm64 architecture, i get the error : "pkg : wrong architecture : FreeBSD:12:amd64 instead of FreeBSD:12:aarch64" 

**To Reproduce**
1. Download package for pfSense plus v22.01 : https://github.com/jaredhendrickson13/pfsense-api/releases/latest/download/pfSense-22.01-pkg-API.txz
2. Start install : "pkg add pfSense-22.01-pkg-API.txz"
3. See error

**Expected behavior**
The package should install without error on arm64 architecture

**Screenshots or Response**
"pkg : wrong architecture : FreeBSD:12:amd64 instead of FreeBSD:12:aarch64"

**pfSense Version & Package Version:**
 - pfSense Version: pfSense plus 22.01 (arm64)
 - Package Version v1.4.2

**Bypass the error**
Steps to bypass the error:
1. Download package for pfSense plus v22.01 : https://github.com/jaredhendrickson13/pfsense-api/releases/latest/download/pfSense-22.01-pkg-API.txz
2. Open files "+MANIFEST" and "+COMPACT_MANIFEST"
3. Replace "FreeBSD:12:amd64" with "FreeBSD:12:aarch64" in both files
4. Start install : "pkg add pfSense-22.01-pkg-API.txz"

**Comment by jaredhendrickson13** [comment]
Hey!

This would be expected behavior at the moment. I actually wasn't aware pfSense Plus ran on ARM so I'm assuming this is exclusive to Netgate appliances, which I do not own. If that's not the case, please let me know.

Otherwise, to be brief, I don't have a build system that can build an ARM-based package currently, and I don't have access to an ARM-based pfSense instance to test the package going forward. So it would technically be considered unsupported at the moment. If they ever release a publicly available version of pfSense on ARM I could start supporting it. In the meantime, I will update documentation to reflect this.

There may be an quicker workaround though. You can try to force the the package to install:

```
pkg add -f https://github.com/jaredhendrickson13/pfsense-api/releases/latest/download/pfSense-22.01-pkg-API.txz && /etc/rc.restart_webgui
```

I do know that doing so will prevent you from updating the API within the UI or using `pfsense-api` command line tool, so you would need to manually uninstall and reinstall the package from the command line with `pkg` anytime you need to update the package. Other than that, I'm not aware of any architecture dependent components of the API, so this _should_ work without issues. But as I mentioned I don't have a ARM-based pfSense instance to verify that. 

Hope this helps.

Thanks!

**Comment by robindbe** [comment]
Hi Jared,

Just as confirmation, I have an ARM machine and forced installed the API and it works just as expected (except for the CLI commands as you mentioned). Tested with some basic alias GET and PUT commands.

**Comment by jwfox5150** [comment]
Confirming that `pkg add -f` still installs pfsense-api correctly on a Netgate 2100 running 23.01.

**Comment by epifeny** [comment]
Confirming this still works as of **April 2026** on `Netgate SG-2100 (ARM Cortex-A53, arm64)` running `pfSense+ 25.11.1-RELEASE (FreeBSD 16.0)`. Installed `v2.7.6` via pkg add using the explicit `25.11.1` build from the releases page. No `-f` flag needed. Key authentication working, REST API v2 endpoints responding correctly.

```
pkg add https://github.com/pfrest/pfSense-pkg-RESTAPI/releases/download/v2.7.6/pfSense-25.11.1-pkg-RESTAPI.pkg
```
