### ISSUE TITLE
create firewall rule not supporting interface groups - get firewall rules does

### ISSUE THREAD

**Issue by dihedral** [jaredhendrickson13/pfsense-api#241]
**Describe the bug**
It seems impossible to add a rule to an interface group - the api returnes an error instead of accepting the interface group name. However, the interface group name is displayed correctly in other rules retrieved through the api.

**To Reproduce**
1. create an interface group
2. add a rule via api

**Expected behavior**
creating a firewall rule using the same name of "interface" as returned by a GET against /api/v1/firewall/rule (so a valid interface group name) should be successfull

**Response**
`{
  "status": "bad request",
  "code": 400,
  "return": 4034,
  "message": "Firewall rule interface required",
  "data": []
}`

**pfSense Version & Package Version:**
 - pfSense Version: 22.01-RELEASE
 - Package Version v1.4.2

**Affected Endpoints:**
 - /api/v1/firewall/rule

**Comment by jaredhendrickson13** [comment]
Hey!

This would be expected behavior for now and is the same situation as #235. To be brief, supporting interface groups in firewall rules could not be covered by tests until an endpoint for creating interfaces groups is available. This would be a feature that would be included when that endpoint Is added.

Thanks!
