### ISSUE TITLE
Allow Modification of WAN IP Address

### ISSUE THREAD

**Issue by leeware** [jaredhendrickson13/pfsense-api#27]
1. I used pfsense-API to make modification to images deployed through automation. 
2. The current API allows me to make one of two changes I need to complete the solution: 
(a) Get and update the VIP  
(b) does not allow me to Update the WAN IP address. 
3. Ideally, it would be great to get the IP address of the WAN and then change it. 
4. It looks like we can delete interfaces (not the WAN) and create new interfaces but we cannot associate a gateway with the WAN IP address.
5.  If we could do number 3 that would be great.

**Comment by jaredhendrickson13** [comment]
Hi!

Thanks for opening this issue. Overhauling the interfaces endpoint is an item that's been backlogged for quite some time. Interfaces are unfortunately one of the more difficult functions to incorporate in the API. I will prioritize implementing interface updates in the endpoint. It is unlikely this will be included in the next release due to the amount of work that has to be done, but I will make this a critical item in the following release. Let me know if there's anything else needed.

Thanks!

**Comment by jaredhendrickson13** [comment]
I was actually able to overhaul the interface endpoint relatively easily. I have the update interface functionality included in my open pull request and will be available during the next release.

Thanks!

**Comment by leeware** [comment]
Jared, 

This is excellent news!   Looking forward to trying it out once the next release is published.

Thank you so much!
