### ISSUE TITLE
How to generate a API token by command line or api?

### ISSUE THREAD

**Issue by JKYLien** [jaredhendrickson13/pfsense-api#281]
Hi,

If I want to generate a API token, is there any way to generate by command line or api?
Because I want to write a script that automates the settings of pfsense from scratch and can use the API Token to operate pfsense, but I am stop at unable to generate a TOKEN to use.

Also, sorry for my bad English~.

**Comment by jaredhendrickson13** [comment]
Hey!

Currently, the only way to generate API tokens is within the UI. This is mostly due to concerns over brute force attacks on API tokens, but coincidentally I am working on implementing pfSense's 'Login Protection' feature within the API authentication which will be available in v1.5.0. I can include the ability to generate API tokens from the API itself alongside that feature. 

I'll update this issue once a pull request contains the feature. 

Thanks!
