### ISSUE TITLE
Some GET parameters works and others don't

### ISSUE THREAD

**Issue by Harryols** [jaredhendrickson13/pfsense-api#317]
**Describe the bug**
Some GET parameters works and others don't. (returns no data, even if there)

**To Reproduce**
  curl --insecure -u admin:pfsense -X 'GET' \
  'https://pfsense.examp.net/api/v1/firewall/nat/port_forward/?local-port=80' \
  -H 'accept: application/json'

**Expected behavior**
I expected to get the port_forwards containing the GET parameter (?local-port=80)

**Screenshots or Response**
{"status":"ok","code":200,"return":0,"message":"Success","data":[]}

**pfSense Version & Package Version:**
 - pfSense Version: 2.6.0-RELEASE (amd64)
 - Package Version: 1.5.1

**Affected Endpoints:**
 - URL: /api/v1/firewall/nat/port_forward
 - Maybe all

**Additional context**
Works fine:
curl --insecure -u admin:pfsense -X 'GET' \
  'https://pfsense.examp.net/api/v1/firewall/nat/port_forward/?target=192.168.1.2' \
  -H 'accept: application/json'

**Comment by jaredhendrickson13** [comment]
Hey!

Looks like this is happening due to the type inference for URL parameters added in feebe80. It's comparing an integer `80` from the request to a string `"80"` from the pfSense config. This would effect most numeric fields and boolean fields. A work around in the meantime is to use JSON query parameters instead to force the types to match. For example:

```
curl --insecure -u admin:pfsense -X 'GET' 
'https://pfsense.examp.net/api/v1/firewall/nat/port_forward/' 
-H 'accept: application/json' -d '{"local-port": "80"}'
```

I'll look into an immediate fix for queries specifically, but a better long term fix is covered by #41 which is planned for v2. 

Thanks!
