### ISSUE TITLE
lik to have pfsense-api for 23.01-release of pfsense 

### ISSUE THREAD

**Issue by berwegera** [jaredhendrickson13/pfsense-api#323]
Hello great project

I have tried to install the api package again on the new 23.01 release:

There are some error messages:

`[23.01-RELEASE][root@pfsense.xyz.com]/root: pkg add /tmp/pfSense-22.05-pkg-API.txz && /etc/rc.restart_webgui                                                        Installing pfSense-pkg-API-1.5_1...
pkg: wrong architecture: FreeBSD:12:amd64 instead of FreeBSD:14:amd64

Failed to install the following 1 package(s): /tmp/pfSense-22.05-pkg-API.txz
[23.01-RELEASE][root@pfsense..xyz.com]/root:
`

Thank you very much fpor the great project!!
Andi

**Comment by jaredhendrickson13** [comment]
Hey!

pfSense Plus 23.01 and pfSense CE 2.7.0 will be supported with API v1.6.0. Previous API versions will not work with these versions of pfSense because 23.01 and 2.7.0 are now using PHP 8.2 on FreeBSD 14; the codebase needed to be refactored.

API v1.6.0 won't be released until pfSense 2.7.0 is released. However, you can use the [development builds](https://github.com/jaredhendrickson13/pfsense-api/releases/tag/v.1.6.0_devc01a130595fc4edd1b) of API v1.6.0 in the meantime to test. These builds may still contain issues so proceed with caution.

Let me know if you have any issues. 

Thanks!

**Comment by berwegera** [comment]
Thank you very much for the fast answer and the hint to the solution!!

And jyes it works like before! No issues.

Thanks again!
Andi

**Comment by zarkod** [comment]
Hello,
The [development builds](https://github.com/jaredhendrickson13/pfsense-api/releases/tag/v.1.6.0_devc01a130595fc4edd1b) link indicated in the post below is incorrect (points to wrong tag v.1.6.0 instead of tag v1.6.0)
I could find them here :
https://github.com/jaredhendrickson13/pfsense-api/releases/tag/v1.6.0_devc01a130595fc4edd1b
Regards,
Manuel 

> Hey!
> 
> pfSense Plus 23.01 and pfSense CE 2.7.0 will be supported with API v1.6.0. Previous API versions will not work with these versions of pfSense because 23.01 and 2.7.0 are now using PHP 8.2 on FreeBSD 14; the codebase needed to be refactored.
> 
> API v1.6.0 won't be released until pfSense 2.7.0 is released. However, you can use the [development builds](https://github.com/jaredhendrickson13/pfsense-api/releases/tag/v.1.6.0_devc01a130595fc4edd1b) of API v1.6.0 in the meantime to test. These builds may still contain issues so proceed with caution.
> 
> Let me know if you have any issues.
> 
> Thanks!
