### ISSUE TITLE
APITools.inc function sort_nat_rules dosn't work with top=true for me

### ISSUE THREAD

**Issue by Rapii** [jaredhendrickson13/pfsense-api#352]
**Describe the bug**
Even if I create a rule with "top=>true" it is added to the end of the rule list.

**pfSense Version & Package Version:**
 - pfSense Version: 2.6.0-RELEASE
 - Package Version: 1.5_3

**Affected Endpoints:**
 - URL: /api/v1/firewall/nat/port_forward

**My Solution**
I have changed line 348 so that the datatype is no longer checked.

"if ($top == true and $idx === $data) {"

Thanks for your great work!

**Comment by jaredhendrickson13** [comment]
Hey!

Thanks for reporting this. This was a bug identified and fixed during the refactor for the coming v1.6.0 release. Since it appears to also effect the current release, I'll look into the feasibility of porting the fix to v1.5.x so it can be applied to pfSense <2.7.0 and <23.01. Shouldn't be a problem.

Thanks!
