### ISSUE TITLE
Create multiple VLANs fails

### ISSUE THREAD

**Issue by riorescue** [jaredhendrickson13/pfsense-api#36]
**PFSense:** 2.4.5-RELEASE-p1 (amd64)
**pfsense-API:** latest

On pfsense machine with 2 interfaces (**vmx0** - wan, **vmx1** - lan), when creating multiple VLANs using the API the result is that only a single VLAN shows in the VLAN list within the administrative GUI. What's interesting is that even though only 1 vlan shows in the VLAN list (the last VLAN created via the API), I am able to see and select all VLANs created through the API using the "Interface Assignments" page.

**Sample Code:**
```
# Create Interfaces and VLANs
vlans = {
    "10": {
        "vlan_interface": "vmx1",
        "vlan_description": "VLAN10-DMZ"
    },
    "18": {
        "vlan_interface": "vmx1",
        "vlan_description": "VLAN18-ALPHAIOT"
    },
    "25": {
        "vlan_interface": "vmx1",
        "vlan_description": "VLAN25-ALPHAGUEST"
    },
    "50": {
        "vlan_interface": "vmx1",
        "vlan_description": "VLAN50-ALPHATRUSTED"
    },
    "51": {
        "vlan_interface": "vmx1",
        "vlan_description": "VLAN51-ALPHAPOLICY"
    },
    "100": {
        "vlan_interface": "vmx1",
        "vlan_description": "VLAN100-CLIENTNET1"
    },
    "200": {
        "vlan_interface": "vmx1",
        "vlan_description": "VLAN200-SRVFARM1"
    },
    "201": {
        "vlan_interface": "vmx1",
        "vlan_description": "VLAN201-SRVFARM2"
    },
}

# Build VLAN Assignments
for key, value in vlans.items():
    print("Building VLAN assignment: " + key + "-" + value['vlan_description'])
    
    parameters = {
        "client-id": PFUsername,
        "client-token": PFPassword,
        "if": value['vlan_interface'],
        "tag": key,
        "descr": value['vlan_description']
    }

    response = requests.post("https://" + PFIPAddress + "/api/v1/interface/vlan", params=parameters, verify=False)
    jprint(response.json())

    # API Wait Time
    time.sleep(5)
```

**Comment by jaredhendrickson13** [comment]
Thanks for reporting this issue. Looks like I am seeing the same behavior on the latest release. I will investigate further and provide an update shortly.

**Comment by jaredhendrickson13** [comment]
I've identified the issue and have an open pull request that contains the patch. A precondition that was intended to initialize the VLAN configuration ended up reverting any existing VLANs before each request. The VLAN interfaces are created correctly on the backend but are not present in pfSense's configuration which is why you see them on the interface assignment page. I should be able to have the patch released either today or tomorrow. Once you have the patched version installed, you can simply rerun your script and the interfaces you are seeing on the interface assignment page will automatically associated themselves with the correct VLAN object in pfSense. Thanks again for reporting!

**Comment by riorescue** [comment]
Verified. Latest release resolves the reported issue. Thanks for the quick work.
