### ISSUE TITLE
aarch64

### ISSUE THREAD

**Issue by phellarv** [jaredhendrickson13/pfsense-api#377]
`# pkg -C /dev/null add https://github.com/jaredhendrickson13/pfsense-api/releases/latest/download/pfSense-2.7-pkg-API.pkg && /etc/rc.restart_webgui
Fetching pfSense-2.7-pkg-API.pkg: 100%    2 MiB   1.7MB/s    00:01    
Installing pfSense-pkg-API-1.6...
pkg: wrong architecture: FreeBSD:14:amd64 instead of FreeBSD:14:aarch64

Failed to install the following 1 package(s): https://github.com/jaredhendrickson13/pfsense-api/releases/latest/download/pfSense-2.7-pkg-API.pkg`

Is it possible to get the API compiled for aarch64?

**Comment by jaredhendrickson13** [comment]
Hey!

This is discussed in #239 and #338. In summary, the only supported architecture is AMD64 since that is the only platform I can perform automated builds and tests on currently. However, the package can still be installed on other architectures by force installing but may have unintended side effects. See #239 for more info.

Thanks!
