### ISSUE TITLE
Create Port Forward Rule ID incorrectly set to 'pass'

### ISSUE THREAD

**Issue by tkrause** [jaredhendrickson13/pfsense-api#39]
When creating a port forwarding rule, the ID is hard coded to 'pass'

This is located here: 

https://github.com/jaredhendrickson13/pfsense-api/blob/master/pfSense-pkg-API/files/etc/inc/api/models/APIFirewallNATPortForwardCreate.inc 

At line 151

```
$this->validated_data["associated-rule-id"] = "pass";
```

In order to support deleting a port forward rule with the API, it needs to be set to 

```
$this->validated_data["associated-rule-id"] = (int)microtime(true);
```

**Comment by jaredhendrickson13** [comment]
Hey!

This is expected behavior. The `associated-rule-id` field is what associates the port forward with a firewall rule, it's not used to identify the port forward itself. Currently, the port forward endpoint only allows the creation of port forwards utilizing the `pass` filter rule association. `pass` is a valid value for this field and is one that is present in the webConfigurator. Since this field is not always unique, the ID used to locate port forwards is the configuration index value (same as what the webConfigurator uses). 

The easiest way to locate the ID of a port forward object is to make a GET request to /api/v1/firewall/port_forward using a query to locate matching object(s). In this example I am trying to locate the ID for a port forward I've made with the description "Test rule" but you can locate the desired object using any field you'd like. You can read more about queries [here](https://github.com/jaredhendrickson13/pfsense-api#queries). The ID will be the array key of the object:

```
$ curl -s -k -d '{"client-id": "admin", "client-token": "pfsense", "descr": "Test rule"}' -X GET https://localhost/api/v1/firewall/nat/port_forward
{
  "status": "ok",
  "code": 200,
  "return": 0,
  "message": "Success",
  "data": {
    "1": { <---- Shows the ID of this object is 1
      "source": {
        "any": ""
      },
      "destination": {
        "network": "wanip",
        "port": "1234"
      },
      "protocol": "tcp",
      "target": "192.168.1.12",
      "local-port": "1234",
      "interface": "wan",
      "descr": "Test rule",
      "associated-rule-id": "pass",
      "updated": {
        "time": "1607470136",
        "username": "admin@172.16.209.1 (Local Database)"
      },
      "created": {
        "time": "1607470136",
        "username": "admin@172.16.209.1 (Local Database)"
      }
    }
  }
}
```

Once you have found your ID, you can add it to your DELETE request payload like such:

```
$ curl -s -k -d '{"client-id": "admin", "client-token": "pfsense", "id": "1"}' -X DELETE https://localhost/api/v1/firewall/nat/port_forward
{
  "status": "ok",
  "code": 200,
  "return": 0,
  "message": "Success",
  "data": {
    "source": {
      "any": ""
    },
    "destination": {
      "network": "wanip",
      "port": "1234"
    },
    "protocol": "tcp",
    "target": "192.168.1.12",
    "local-port": "1234",
    "interface": "wan",
    "descr": "Test rule",
    "associated-rule-id": "pass",
    "updated": {
      "time": "1607470136",
      "username": "admin@172.16.209.1 (Local Database)"
    },
    "created": {
      "time": "1607470136",
      "username": "admin@172.16.209.1 (Local Database)"
    }
  }
}
```

A future release (most likely v1.2.0), will introduce framework adjustments that include the ID in the API response data which will make this more transparent and more REST like. Let me know if you have any troubles locating the IDs for any of the endpoints.

Thanks!

**Comment by GigaTech** [comment]
Give some love to #318, same issue
