### ISSUE TITLE
Delete nat on_to_one mapping

### ISSUE THREAD

**Issue by h-medjahed** [jaredhendrickson13/pfsense-api#42]
Hi I am wandering how to perform the delete of nat one_to_one mapping where an id is expected in the request, considering that when we performe list (read) nat one_to_one the id is not available in the response.

**Comment by jaredhendrickson13** [comment]
Hey there!

This is a great question. The ID is actually available in the response data from GET requests, just probably not in the way you'd expect. pfSense unfortunately does not create unique identifiers for each object, rather it uses the objects configuration index value to identify the object. This is the case for all objects returned via the API as well unless stated otherwise stated in the documentation.

For example, if you make a GET request to the 1:1 NAT endpoint you will get a list of 1:1 NAT objects. The ID for each object will be the array index of the object within the data field:
```js
{
  "status": "ok",
  "code": 200,
  "return": 0,
  "message": "Success",
  "data": [
    // This object is ID 0
    {
      "external": "1.2.3.4",
      "descr": "Test 1:1 NAT rule",
      "interface": "wan",
      "source": {
        "address": "172.16.209.50"
      },
      "destination": {
        "any": ""
      }
    },
    // This object is ID 1, we'll say this is the object I am trying to delete
    {
      "external": "4.3.2.1",
      "descr": "Another test 1:1 NAT rule ",
      "interface": "wan",
      "source": {
        "address": "172.16.209.51"
      },
      "destination": {
        "network": "lanip"
      },
      "natreflection": "enable"
    },
   // This object is ID 2
    {
      "external": "3.2.1.0",
      "descr": "Last test 1:1 NAT rule ",
      "interface": "wan",
      "source": {
        "address": "172.16.209.52"
      },
      "destination": {
        "any": ""
      },
      "natreflection": "enable"
    }
  ]
}
```

From here I can use the ID to delete the corresponding object:
```
$ curl -k -s -H "Content-Type: application/json" -d '{"client-id": "admin", "client-token": "pfsense", "id": 1}' -X DELETE 
https://localhost/api/v1/firewall/nat/one_to_one
```
```json
{
  "status": "ok",
  "code": 200,
  "return": 0,
  "message": "Success",
  "data": {
    "external": "4.3.2.1",
    "descr": "Another test 1:1 NAT rule ",
    "interface": "wan",
    "source": {
      "address": "172.16.209.51"
    },
    "destination": {
      "network": "lanip"
    },
    "natreflection": "enable"
  }
}
```

Keep in mind the IDs are dynamic, after an object is deleted the remaining items will be sorted. This means that after I delete ID 1, ID 2 now becomes ID 1. It is important for your scripts to make a GET request beforehand to verify the ID before attempting to delete or update an object. 

Hopefully this helps, let me know if I can provide any further assistance.

Thanks!

**Comment by h-medjahed** [comment]
Thank you for your answer and for specifying that we need to keep in mind the IDs are dynamic.
