### ISSUE TITLE
RESTAPI (v2) - DHCP Server Custom Options

### ISSUE THREAD

**Issue by crawc** [jaredhendrickson13/pfsense-api#466]
**Describe the bug**
DHCP Custom Options Missing from GET & PATCH

**To Reproduce**
1. Go to DHCP Server in the GUI /services_dhcp.php
2. Enable and configure a DHCP Server with the required setting.
3. Create a custom option:
option 66, string, "https://boot-server"
4. Save
5. From the API (/api/v2/services/dhcp_servers?limit=0&offset=0) and the custom DHCP options are missing. Same for the create (PATCH) API call.

**Expected behavior**
Return the custom DHCP options & Edit/create custom DHCP options.

**pfSense Version & Package Version:**
 - pfSense Version: pfSense 2.7.2
 - Package Version: v2.0.0-dev-3982522

**Affected Endpoints:**
 - URL: 
 GET /api/v2/services/dhcp_servers ?limit=0&offset=0
 GET/PATCH: /api/v2/services/dhcp_server

**Comment by jaredhendrickson13** [comment]
Thanks for bringing this up. This was somewhat intentional. Initially the plan was for the v2 endpoints to be based completely on Kea DHCP instead of ISC DHCP like v1. The pfSense implementation of Kea DHCP currently doesn't support the DHCP custom options which is why it is missing from v2; it was just never planned to port that model over from v1. I backpedaled a bit on the initial plan later on and added some of the ISC DHCP specific features back into v2 and made the DHCP backend configurable. This feature should probably also be added back in that case. I should be able to have that added back before v2 goes beta.

**Comment by crawc** [comment]
That would be excellent! Thank you!

I have yet to even start with Kea DHCP in pfSense so I wasn't aware it was missing there.

**Comment by jaredhendrickson13** [comment]
Implemented in https://github.com/jaredhendrickson13/pfsense-api/releases/tag/v2.0.0-dev-f207e6f
