### ISSUE TITLE
The creation firewall NAT1TO1 induces changes of the outbound NAT mode

### ISSUE THREAD

**Issue by h-medjahed** [jaredhendrickson13/pfsense-api#47]
When we create a firewall NAT 1TO1 mapping with this API, the firewall outbound NAT mode is switching to automatic.
I am wondering why this behavior because if we perform the same action through the user interface, there is no change on the firewall outbound NAT which is a logic behavior.

**Comment by h-medjahed** [comment]
To overcome this issue you have to modify models/APIFirewallNATOneToOneCreate.inc ligne 34
remove this line  $this->config["nat"] = [];

**Comment by jaredhendrickson13** [comment]
Thanks for reporting this issue. This looks to be a bug. The entire NAT configuration gets reinitialized when the model sees the one-to-one configuration requires initialization. 

https://github.com/jaredhendrickson13/pfsense-api/blob/acddc9c4441220ace9130cd3b5e0231cef47b237/pfSense-pkg-API/files/etc/inc/api/models/APIFirewallNATOneToOneCreate.inc#L34
Like you mentioned, removing this line will fix the issue, but only if the NAT configuration has already been initialized. Otherwise an error will be thrown due to the NAT configuration not being initialized before the one-to-one configuration.

I will work on a fix to implement stronger pre-condition checks for the configuration initialization.

Thanks!
