### ISSUE TITLE
Update to Dev version

### ISSUE THREAD

**Issue by itguy327** [jaredhendrickson13/pfsense-api#474]
I tried to install the dev version using the following and it installed 1.7.3 - I also tried to update to the dev version via the UI but it does not appear to work. 

pkg -C /dev/null add https://github.com/jaredhendrickson13/pfsense-api/releases/download/v2.0.0-dev-990b919/pfSense-2.7.2-pkg-RESTAPI.pkg && /etc/rc.restart_webgui

Thank you for all your work.

**Comment by jaredhendrickson13** [comment]
This is likely because v1 and v2 are separate packages that can be installed concurrently. 

- The v1 package's internal name is pfSense-pkg-API and the settings can be found within the UI under System > API.
- The v2 package's internal name is pfSense-pkg-RESTAPI can the settings can be found within the UI under System > REST API

Run `pkg info pfSense-pkg-RESTAPI` to see what v2 version is installed.

**Comment by itguy327** [comment]
Thanks. Didn't realize it changed the cli command or the menu entry.

My bad. Thank you again

Best Regards,
Jason Quackenbush
