### ISSUE TITLE
v1 update to v2

### ISSUE THREAD

**Issue by ouyoung33** [jaredhendrickson13/pfsense-api#487]
I use the directive "pkg -C /dev/null add https://github.com/jaredhendrickson13/pfsense-api/releases/latest/download/pfSense-2.7-pkg-API.pkg && /etc/rc.restart_webgui
"After the installation is complete, the api interface shows v1 version, I want to upgrade to v2, and then use the directive" pfsense-api update
It says "Command not found", so how do I upgrade to v2

**Comment by jaredhendrickson13** [comment]
v1 and v2 are separate packages to allow them to be installed concurrently. Because of this there is no direct upgrade path from v1 to v2, instead you just install v2 as a new installation. To install the latest release candidate for v2:

```
pkg-static -C /dev/null add https://github.com/jaredhendrickson13/pfsense-api/releases/download/v2.0.0-rc-30b2715/pfSense-2.7.2-pkg-RESTAPI.pkg
```

Few things to keep in mind:

- The v1 package's CLI tool is named `pfsense-api` whereas the v2 package's CLI tool is named `pfsense-restapi`. These two are not interchangeable and they can only be used to manage the corresponding package.
- The v1 package's UI page is found at System > API whereas the v2 package's UI page is found at System > REST API. These pages and settings are also not interchangeable and can only be used to configure the corresponding package.
- v2 is still currently a pre-release stage (release candidate). A full release is expected before the end of this month.
