### ISSUE TITLE
Incorrect disabled user check in APIAuth::authenticate_token()

### ISSUE THREAD

**Issue by 0xF-zz** [jaredhendrickson13/pfsense-api#50]
I've noticed that the disabled user check in APIAuth::authenticate_token() incorrectly passes the client-id to the check:

`if (APITools\is_user_disabled($this->request["client-id"]) === false) {`

It's implemented correctly for the other authentication mechanisms:

`if (APITools\is_user_disabled($this->username) === false) {`

Please let me know if you prefer that I open a bug fix PR - I figured it's such a minor change that it's probably not worth the overhead.

Anyway, thank you for this awesome project!

**Comment by jaredhendrickson13** [comment]
Good catch, thanks for reporting this! This is an important one to fix since it appears to allow disabled users to authenticate if they have existing API tokens. You are welcome to open a pull request with this change, that is probably the best way to receive credit for your finding. Otherwise, I will make the change before the next release.

Thanks again!

**Comment by 0xF-zz** [comment]
No need for credit, happy to help. Appreciate your work!
