### ISSUE TITLE
Missing group of api endpoints in v2

### ISSUE THREAD

**Issue by droid-sheep** [jaredhendrickson13/pfsense-api#501]
**Describe the bug**

After freshly installing the pfrest pkg (pfSense-2.7.2-pkg-RESTAPI.pkg) some endpoint groups are not available (HTTP 404).
Following groups of endpoints are not available (referencing https://pfrest.org/api-docs/#/): 
- system 
- user
- vpn

**To Reproduce**

1. Install pkg via pfsense command line:
    `pkg-static -C /dev/null add https://github.com/jaredhendrickson13/pfsense-api/releases/latest/download/pfSense-2.7.2-pkg-RESTAPI.pkg`
2. Switch Authentication to KEY based only
3. Create a REST Key under keys tab. Hashing = SHA256, Length = 16
4. Call via REST API Client (i used Advanced Rest client):
```
GET https://<fw>/api/v2/system/crls
Headers:
X-API-Key: <API Key>
```
Response:
```
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Expected behavior**
Response defined in api docs and not a HTTP 404 error.

**Screenshots or Response**
-/-

**pfSense Version & Package Version:**

- pfSense Version:  2.7.2-RELEASE (amd64)
- Package Version: pfSense REST API v2.0.0 for 2.7.2

**Affected Endpoints:**

- URL: /api/v2/system/**
- URL: /api/v2/user/**
- URL: /api/v2/vpn/**

**Additional context**
-/-

**Comment by jaredhendrickson13** [comment]
These are all present for me after installing. Try running `pfsense-restapi buildendpoints` from the command line to force the endpoints to be rebuilt.

**Comment by droid-sheep** [comment]
When i execute your mentioned command in the web debug command line i get this response:
```
Building endpoints...
Fatal error: Uncaught RESTAPI\Responses\ServerError: Cannot parse FloatField `cpu_load_avg` from internal because its internal value is not
                    a numeric value. Consider changing this field to a StringField. in /usr/local/pkg/RESTAPI/Fields/FloatField.inc:143
Stack trace:
#0 /usr/local/pkg/RESTAPI/Core/Field.inc(886): RESTAPI\Fields\FloatField->_from_internal('0,18 0,22 0,23')
#1 /usr/local/pkg/RESTAPI/Core/Model.inc(827): RESTAPI\Core\Field->from_internal('0,18 0,22 0,23')
#2 /usr/local/pkg/RESTAPI/Core/Model.inc(810): RESTAPI\Core\Model->from_internal_object(Array)
#3 /usr/local/pkg/RESTAPI/Core/Model.inc(354): RESTAPI\Core\Model->from_internal()
#4 /usr/local/pkg/RESTAPI/Core/Model.inc(296): RESTAPI\Core\Model->construct_from_internal(NULL, NULL)
#5 /usr/local/pkg/RESTAPI/Models/SystemStatus.inc(162): RESTAPI\Core\Model->__construct(NULL, NULL, Array)
#6 /usr/local/pkg/RESTAPI/Core/Endpoint.inc(272): RESTAPI\Models\SystemStatus->__construct()
#7 /usr/local/pkg/RESTAPI/Endpoints/StatusSystemEndpoint.inc(21): RESTAPI\Core\Endpoint->__construct()
#8 /usr/local/pkg/RESTAPI/.resources/scripts/manage.php(40): RESTAPI\Endpoints\StatusSystemEndpoint->__construct()
#9 /usr/local/pkg/RESTAPI/.resources/scripts/manage.php(412): build_endpoints()
#10 {main}
  thrown in /usr/local/pkg/RESTAPI/Fields/FloatField.inc on line 143
PHP ERROR: Type: 1, File: /usr/local/pkg/RESTAPI/Fields/FloatField.inc, Line: 143, Message: Uncaught RESTAPI\Responses\ServerError: Cannot parse FloatField `cpu_load_avg` from internal because its internal value is not
                    a numeric value. Consider changing this field to a StringField. in /usr/local/pkg/RESTAPI/Fields/FloatField.inc:143
Stack trace:
#0 /usr/local/pkg/RESTAPI/Core/Field.inc(886): RESTAPI\Fields\FloatField->_from_internal('0,18 0,22 0,23')
#1 /usr/local/pkg/RESTAPI/Core/Model.inc(827): RESTAPI\Core\Field->from_internal('0,18 0,22 0,23')
#2 /usr/local/pkg/RESTAPI/Core/Model.inc(810): RESTAPI\Core\Model->from_internal_object(Array)
#3 /usr/local/pkg/RESTAPI/Core/Model.inc(354): RESTAPI\Core\Model->from_internal()
#4 /usr/local/pkg/RESTAPI/Core/Model.inc(296): RESTAPI\Core\Model->construct_from_internal(NULL, NULL)
#5 /usr/local/pkg/RESTAPI/Models/SystemStatus.inc(162): RESTAPI\Core\Model->__construct(NULL, NULL, Array)
#6 /usr/local/pkg/RESTAPI/Core/Endpoint.inc(272): RESTAPI\Models\SystemStatus->__construct()
#7 /usr/local/pkg/RESTAPI/Endpoints/StatusSystemEndpoint.inc(21): RESTAPI\Core\Endpoint->__construct()
#8 /usr/local/pkg/RESTAPI/.resources/scripts/manage.php(40): RESTAPI\Endpoints\StatusSystemEndpoint->__construct()
#9 /usr/local/pkg/RESTAPI/.resources/scripts/manage.php(412): build_endpoints()
#10 {main}
  thrown
```

**Comment by droid-sheep** [comment]
@jaredhendrickson13 
Okay now i found something! Executing the `pfsense-restapi buildendpoints` command in the virtual machine shell gives me:
```
Building endpoints... done.
Building privileges... done.
```
After that (quick look) all endpoints work now. I don't know why the command doesn't work in the web debug shell. Also maybe there is a difference if i execute the install command in the web php prompt or in a "real" shell.

Maybe further investigate this or add an disclaimer to the install section that users shouldn't use the web debug shell.

I leave it up to you if you want to close this issue or investigate. Thank you for the rebuild command, it solved my issue.

**Comment by jaredhendrickson13** [comment]
Actually, the error you received previously does show a valid issue which could be preventing the endpoints from building correctly. The CPU load averages on your system are/were formatted with commas as the decimal separator instead of points as PHP expects them, which is valid for certain regions around the world. Regardless, the logic of the underlying models probably shouldn't prevent the endpoints from being built, so I'll work on a fix for those things.

Thanks!

**Comment by corgan2222** [comment]
I was facing the same error with the newest version, if the pfsense language is set to german.
After switching to english, it works.


Version | 2.7.2-RELEASE 				(amd64)

`
Crash report begins.  Anonymous machine information:

amd64
14.0-CURRENT
FreeBSD 14.0-CURRENT amd64 1400094 #1 RELENG_2_7_2-n255948-8d2b56da39c: Wed Dec  6 20:45:47 UTC 2023     root@freebsd:/var/jenkins/workspace/pfSense-CE-snapshots-2_7_2-main/obj/amd64/StdASW5b/var/jenkins/workspace/pfSense-CE-snapshots-2_7_2-main/sources/F

Crash report details:

PHP Errors:
[20-Jan-2025 11:00:09 Europe/Berlin] PHP Fatal error:  Uncaught RESTAPI\Responses\ServerError: Cannot parse FloatField `cpu_load_avg` from internal because its internal value is not
                    a numeric value. Consider changing this field to a StringField. in /usr/local/pkg/RESTAPI/Fields/FloatField.inc:146
Stack trace:
#0 /usr/local/pkg/RESTAPI/Core/Field.inc(894): RESTAPI\Fields\FloatField->_from_internal('0.64 0.57 0.56')
#1 /usr/local/pkg/RESTAPI/Core/Model.inc(910): RESTAPI\Core\Field->from_internal('0,64 0,57 0,56')
#2 /usr/local/pkg/RESTAPI/Core/Model.inc(882): RESTAPI\Core\Model->from_internal_object(Array)
#3 /usr/local/pkg/RESTAPI/Core/Model.inc(427): RESTAPI\Core\Model->from_internal()
#4 /usr/local/pkg/RESTAPI/Core/Model.inc(327): RESTAPI\Core\Model->construct_from_internal(NULL, NULL)
#5 /usr/local/pkg/RESTAPI/Models/SystemStatus.inc(162): RESTAPI\Core\Model->__construct(NULL, NULL, Array)
#6 /usr/local/pkg/RESTAPI/Models/RESTAPISettings.inc(238): RESTAPI\Models\SystemStatus->__construct()
#7 /usr/local/pkg/RESTAPI/Core/Field.inc(319): RESTAPI\Models\RESTAPISettings->get_override_sensitive_fields_choices()
#8 /usr/local/pkg/RESTAPI/Core/Field.inc(1125): RESTAPI\Core\Field->set_choices_from_callable()
#9 /usr/local/pkg/RESTAPI/Core/Form.inc(195): RESTAPI\Core\Field->to_form_input()
#10 /usr/local/pkg/RESTAPI/Core/Form.inc(354): RESTAPI\Core\Form->get_form()
#11 /usr/local/www/system_restapi_settings.php(10): RESTAPI\Core\Form->print_form()
#12 {main}
  thrown in /usr/local/pkg/RESTAPI/Fields/FloatField.inc on line 146
[20-Jan-2025 11:00:46 Europe/Berlin] PHP Fatal error:  Uncaught RESTAPI\Responses\ServerError: Cannot parse FloatField `cpu_load_avg` from internal because its internal value is not
                    a numeric value. Consider changing this field to a StringField. in /usr/local/pkg/RESTAPI/Fields/FloatField.inc:146
Stack trace:
#0 /usr/local/pkg/RESTAPI/Core/Field.inc(894): RESTAPI\Fields\FloatField->_from_internal('0.38 0.51 0.54')
#1 /usr/local/pkg/RESTAPI/Core/Model.inc(910): RESTAPI\Core\Field->from_internal('0,38 0,51 0,54')
#2 /usr/local/pkg/RESTAPI/Core/Model.inc(882): RESTAPI\Core\Model->from_internal_object(Array)
#3 /usr/local/pkg/RESTAPI/Core/Model.inc(427): RESTAPI\Core\Model->from_internal()
#4 /usr/local/pkg/RESTAPI/Core/Model.inc(327): RESTAPI\Core\Model->construct_from_internal(NULL, NULL)
#5 /usr/local/pkg/RESTAPI/Models/SystemStatus.inc(162): RESTAPI\Core\Model->__construct(NULL, NULL, Array)
#6 /usr/local/pkg/RESTAPI/Models/RESTAPISettings.inc(238): RESTAPI\Models\SystemStatus->__construct()
#7 /usr/local/pkg/RESTAPI/Core/Field.inc(319): RESTAPI\Models\RESTAPISettings->get_override_sensitive_fields_choices()
#8 /usr/local/pkg/RESTAPI/Core/Field.inc(1125): RESTAPI\Core\Field->set_choices_from_callable()
#9 /usr/local/pkg/RESTAPI/Core/Form.inc(195): RESTAPI\Core\Field->to_form_input()
#10 /usr/local/pkg/RESTAPI/Core/Form.inc(354): RESTAPI\Core\Form->get_form()
#11 /usr/local/www/system_restapi_settings.php(10): RESTAPI\Core\Form->print_form()
#12 {main}
  thrown in /usr/local/pkg/RESTAPI/Fields/FloatField.inc on line 146
[20-Jan-2025 11:02:44 Europe/Berlin] PHP Fatal error:  Uncaught RESTAPI\Responses\ServerError: Cannot parse FloatField `cpu_load_avg` from internal because its internal value is not
                    a numeric value. Consider changing this field to a StringField. in /usr/local/pkg/RESTAPI/Fields/FloatField.inc:146
Stack trace:
#0 /usr/local/pkg/RESTAPI/Core/Field.inc(894): RESTAPI\Fields\FloatField->_from_internal('0.30 0.42 0.49')
#1 /usr/local/pkg/RESTAPI/Core/Model.inc(910): RESTAPI\Core\Field->from_internal('0,30 0,42 0,49')
#2 /usr/local/pkg/RESTAPI/Core/Model.inc(882): RESTAPI\Core\Model->from_internal_object(Array)
#3 /usr/local/pkg/RESTAPI/Core/Model.inc(427): RESTAPI\Core\Model->from_internal()
#4 /usr/local/pkg/RESTAPI/Core/Model.inc(327): RESTAPI\Core\Model->construct_from_internal(NULL, NULL)
#5 /usr/local/pkg/RESTAPI/Models/SystemStatus.inc(162): RESTAPI\Core\Model->__construct(NULL, NULL, Array)
#6 /usr/local/pkg/RESTAPI/Models/RESTAPISettings.inc(238): RESTAPI\Models\SystemStatus->__construct()
#7 /usr/local/pkg/RESTAPI/Core/Field.inc(319): RESTAPI\Models\RESTAPISettings->get_override_sensitive_fields_choices()
#8 /usr/local/pkg/RESTAPI/Core/Field.inc(1125): RESTAPI\Core\Field->set_choices_from_callable()
#9 /usr/local/pkg/RESTAPI/Core/Form.inc(195): RESTAPI\Core\Field->to_form_input()
#10 /usr/local/pkg/RESTAPI/Core/Form.inc(354): RESTAPI\Core\Form->get_form()
#11 /usr/local/www/system_restapi_settings.php(10): RESTAPI\Core\Form->print_form()
#12 {main}
  thrown in /usr/local/pkg/RESTAPI/Fields/FloatField.inc on line 146



No FreeBSD crash data found.
			`
