### ISSUE TITLE
OpenVPN Client Status

### ISSUE THREAD

**Issue by kemalevren** [jaredhendrickson13/pfsense-api#514]
I am using version 1.7.0 of the pfsense-api package in my project and would like to upgrade to version 2.0.0. However, I have some dependencies and I can't find certain endpoints in the new version. For example, the status/openvpn endpoint is not available in version 2.0.0. I would like to know if this endpoint has been removed or if it has been replaced by another endpoint. Can you help me with this?

Thx.

**Comment by jaredhendrickson13** [comment]
Yeah there are still a small handful of endpoints that haven't been ported over to v2 yet. Mostly due to unpredictability in the pfSense functions that return the relevant data for those endpoints. Since v2 enforces strict schema, those endpoints  become error prone if the structure of the data suddenly changes. It is mostly the 'status' endpoints that fall into this category unfortunately.

That being said, they are actively being worked on and will make a return in v2 in the near future. In the meantime, v1 and v2 can be installed concurrently to allow you to continue to use the v1 endpoints you need while also utilizing the new v2 endpoints.

I'll update this issue as progress is made on that specific endpoint.

Thanks!
