### ISSUE TITLE
PATCH method on "/api/v2/firewall/nat/port_forward" , always getting error in "associated_rule_id" field.

### ISSUE THREAD

**Issue by poshl9k** [jaredhendrickson13/pfsense-api#518]
**Describe the bug**
PATCH method on "/api/v2/firewall/nat/port_forward" , always getting error in "associated_rule_id" field.

```
curl -X 'PATCH' \
  'http://x.x.x.x/api/v2/firewall/nat/port_forward' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic xxxxx' \
  -H 'Content-Type: application/json' \
  -d '{
  "id": 0,
  "disabled": true,
  "associated_rule_id": "nat_669e4fc9db81b5.86263762",
}'
```
**associated_rule_id gotten from /api/v2/firewall/nat/port_forwards**

```
{
  "code": 400,
  "status": "bad request",
  "response_id": "FIELD_INVALID_CHOICE",
  "message": "Field `associated_rule_id` must be one of [, pass]",
  "data": []
}.
```

**To Reproduce**

1. Go to pfsense api/documentation
2. Click on /api/v2/firewall/nat/port_forwards and execute
3. Get 'id' and 'associated_rule_id' of needed rule
4. Click on /api/v2/firewall/nat/port_forwards and execute
5. fill test json fields: 
`id`, 
`associated_rule_id` (because we cant go without it, but no reference about it in doc), 
`disabled`
6. See error

by the way everything is the same with python requests.

**Expected behavior**
not changing unnecessary fields.
if it really needed: using `associated_rule_id` from pfsense NAT rule or firewall rule `id`

**Screenshots or Response**

**pfSense Version & Package Version:**
- pfSense Version: 2.7.2-RELEASE 
- Package Version v2.0.2

**Affected Endpoints:**
- URL: /api/v2/firewall/nat/port_forwards
- URL: /api/v2/firewall/nat/port_forward

Thanks in advance! Totaly cool pkg, by the way, really appreciate your work!

**Comment by jaredhendrickson13** [comment]
This would be expected behavior as of right now. This endpoint currently only supports `pass` or an empty string (for unassociated filter rules) as the `associated_rule_id`:

<img width="1431" alt="Screenshot 2024-07-22 at 1 16 07 PM" src="https://github.com/user-attachments/assets/0928db64-a27a-4914-9c18-c78809d9d168">

 If you added the port forward from the webConfigurator and set the 'Filter rule association' to 'Create a new associated filter rule', the endpoint will not accept the update until the `associated_rule_id` is changed to an option allowed by the REST API. You receive the error even with a partial update because the entire object still must be revalidated after any value changes to ensure there are no conflicts between existing values and changed values. 

There is an open feature request (#275) to allow associated filter rules which should be picked up for v2.1.0. You can follow that issue for any updates.

Thanks!

**Comment by poshl9k** [comment]
Thanks for explanation. I'll follow that request
