### ISSUE TITLE
Cannot create Rule use Gateway in "Gateway Groups"

### ISSUE THREAD

**Issue by longnv107** [jaredhendrickson13/pfsense-api#52]
I can create a rule with a default gateway or gateway in "Gateways Tab". But cannot create use Gateways in "Gateway Groups Tab".
How can I do it ?
Thanks

**Comment by jaredhendrickson13** [comment]
Hey!

Looking at the code, only singular gateway items are being allowed when creating or updating firewall rules and there is no way to add a gateway group to firewall rules via API at this time. I don't remember off the top of my head if this was intentional or just an oversight. I think this should be an easy fix, but I'll take a closer look sometime this week to be sure. If so, I can have this functionality added in the next patch. 

Thanks!

**Comment by longnv107** [comment]
Thanks Bro. Expecting next Patch.
