### ISSUE TITLE
Update firewall alias

### ISSUE THREAD

**Issue by h-medjahed** [jaredhendrickson13/pfsense-api#56]
When we try to update a firewall alias we get {"status":"bad request","code":400,"return":4056,"message":"Firewall alias already exists","data":[]}

**Comment by jaredhendrickson13** [comment]
Hey!

This was a known issue fixed in [v1.1.2](https://github.com/jaredhendrickson13/pfsense-api/releases/tag/v1.1.2). If you haven't already, update the package and that should get things working. Otherwise, if you are still experiencing this issue on v1.1.2, please provide the request data you are using when you receive this error and I can take a closer look. 

Thanks!

**Comment by h-medjahed** [comment]
I confirm that the issue is fixed in v1.1.2.
