### ISSUE TITLE
APIFirewallRuleSort missing from v2 api?

### ISSUE THREAD

**Issue by cdalamagkas** [jaredhendrickson13/pfsense-api#565]
Starting from the v1.4.0 of the REST API, the `/api/v1/firewall/rule/sort` endpoint was added (#133), however, this feature does not exist on the v2.1.2 of the API. 

Is this a bug? Is it planned to re-introduce the feature for the API v2?

**Comment by jaredhendrickson13** [comment]
It was an intentional decision. One of the main goals for v2 was to reduce feature and code duplication. Since sorting isn't unique to firewall rules and could be useful for multiple endpoints, I decided not to carry over that specific endpoint into v2. Instead, a standard sorting feature is being worked on (right now actually) that will work the same way, but can be used across any endpoint interacting with configuration objects. You'll be able to manage it through new [control parameters](https://pfrest.org/COMMON_CONTROL_PARAMETERS/), and it should be available in v2.2.0 later this month or early next month.
