### ISSUE TITLE
firewall states read not returning valid data

### ISSUE THREAD

**Issue by george-vieira** [jaredhendrickson13/pfsense-api#57]
States output not correct or being parsed properly. Also API doesn't appear to support killing any existing states/connections which I need too.
(a.b.c.d is my public ip.)

{
  "interface": "pppoe0",
  "protocol": "tcp",
  "source": "->",
  "destination": "a.b.c.d:48517",
  "status": "74.125.28.188:5228"
}

**Comment by jaredhendrickson13** [comment]
Hey!

Thanks for reporting. Looks like the parsing issue is caused by extra fields added in PPPoE interface states. I don't have a way to test PPPoE configurations unfortunately so it was overlooked. Found an easier option for parsing states so I can have a fix included in the next patch. 

As for killing firewall states, I have been working to implement this feature for sometime but unfortunately pfSense handles this task asynchronously and there are undesired behaviors to work out before I can release it. It should hopefully be included in the next minor release.

I'll update this issue when I have a PR with the parsing fix.

Thanks!

**Comment by george-vieira** [comment]
I can provide some output from CLI you can use as unittest/fake data if it help.

With the async issue, the API caller can poll for the status or if their changes have completed. etc.
