### ISSUE TITLE
Problem update V1 to V2

### ISSUE THREAD

**Issue by Gsyltc** [jaredhendrickson13/pfsense-api#612]
**Describe the bug**
Hello,

I have a problem updating to the API V2.
I use the command

 `pkg-static -C /dev/null add https://github.com/jaredhendrickson13/pfsense-api/releases/download/v2.0.0/pfSense-2.7.2-pkg-RESTAPI.pkg`

output : 
`
Fetching pfSense-2.7.2-pkg-RESTAPI.pkg: .......... done    
Installing pfSense-pkg-RESTAPI-2.0...    
the most recent version of pfSense-pkg-RESTAPI-2.2_2 is already installed
`

When I go to System -> API -> Update the current version is v1.7.1 - Update available

When I click on the Update button on this page I have this message : 
`The changes have been applied successfully. The API update process has started and is running in the background. Check in a few minutes.`

I wait about 15min, refresh the page and it still on V1.7.1

Did I miss a step? 

Thanks

PFSense Version : 2.7.2-RELEASE (amd64)
`
pfsense-restapi version 

pfSense-pkg-RESTAPI-2.2_2
Name           : pfSense-pkg-RESTAPI
Version        : 2.2_2
Installed on   : Thu Dec  5 10:50:48 2024 EST
Origin         : sysutils/pfSense-pkg-RESTAPI
Architecture   : FreeBSD:14:*
Prefix         : /usr/local
Categories     : sysutils
Licenses       : APACHE20
Maintainer     : github@jaredhendrickson.com
WWW            : UNKNOWN
Comment        : pfSense REST API package
Annotations    :
Flat size      : 6.89MiB
Description    :
The missing REST API package for pfSense.
`

**Comment by jaredhendrickson13** [comment]
v1 and v2 are released as separate packages so they can be installed concurrently on the same system. v1 will be under System > API and use the `pfsense-api` command line tool, whereas v2 is under System > REST API and uses the `pfsense-restapi` tool. 

There was a bug in v1 that allowed it to see v2 releases as valid upgrade candidates, but in reality it just installed the v2 package alongside v1. That was fixed in v1.7.5. Now v1 only sees v1 releases as upgrade candidates, and v2 only sees v2 releases as upgrade candidates.

Let me know if you have any further issues.
