### ISSUE TITLE
Issues Updating The WAN Interface IP via the API call from PowerShell

### ISSUE THREAD

**Issue by leeware** [jaredhendrickson13/pfsense-api#64]
Jared,  

Thank you for creating the ability to update the WAN IP Addresses.  The problem I seem to be stuck on is how to properly format the request to  to update the IP address from PowerShell.  I am able to update the Virtual IP address using the following request: 

$VirtualIP = "2.2.2.2"
Invoke-RestMethod - Uri "https://1.1.1.1/api/v1/firewall/virtual_ip/?client-id=Username&client-token=Password&id=0&subnet=$($VirtualIP)&interface=wan" -Method PUT

It appears that no matter what I do to update the WAN Interface IP, I get a 400 error.

$WANIPAddress = "3.3.3.3"
Invoke-RestMethod - Uri "https://1.1.1.1/api/v1/interface/?client-id=Username&client-token=Password&if=em0&enable=true&type=staticv4&ipaddr=$($WANIPAddress)$subnet=24$blockgons=true" -Method PUT

Also when I try to get the interface values from powershell , the commands are successful but they basically do not appear to return any data.  So I can't tell if the problem is just my requests or if something is not working as expected.  

I am presuming the former.  Any insights would be appreciated.  

Thanks again.

**Comment by jaredhendrickson13** [comment]
Hey!

I'm assuming you are running the latest version of the API, if not try the request using the latest version and see if anything changes. I'm not very familiar with PowerShell unfortunately so I'm not entirely sure why you would not receive any response. When using curl I seem to get the expected response. However, looking at your interface request there are a few things that may be happening here:

1) I don't see a parameter for the required `id` field. This should be the existing interface you are trying to update. In this case `id=wan` would be needed in your parameter string to correctly target the WAN interface. Otherwise an error will be returned.

2) Unless you are specifically trying to change the physical interface associated with the interface object, don't include the `if` parameter even if it contains the same physical interface. It returns an error stating that the physical interface is already in use. This is a known bug that I will have patched soon, but a simple workaround in the meantime is to just not specify the `if` parameter in your PUT request.

3) Note sure if this is just a copy and paste issue or something, but your request's parameter string incorrectly uses `$` as the parameter delimiter before the `subnet` and `blockbogons` parameters. This should be `&` instead.

4) If possible, you may want to try to format the content body as JSON instead of URL encoded parameters. URL encoded parameters technically should work, but the API was primarily designed around JSON content so there may be a parsing issue there.

Hopefully this helps. If you run into any more issue let me know and I can take a deeper look. 

Thanks!

**Comment by leeware** [comment]
Jared,  

You for the timely response. 

1. I realized this might be an issue when I was testing.  I could not update it, I just install the API again which got me the latest version.  I had done this part prior to my post.

2. Your second recommendation was helpful leaving out the interface was part of my issue.

3. I corrected the typos in the powershell  -- I think I was having a combination of problems and your response helped me to me to resolve the issues I was seeing.  

4. I have been able to make the change after correcting the commands.

5. I was able to commit the changes by making the post call to /api/v1/interface/apply/ 

$WANIPAddress = "3.3.3.3"
Invoke-RestMethod - Uri "https://1.1.1.1/api/v1/interface/?client-id=Username&client-token=Password&id=wan&enable=true&type=staticv4&ipaddr=$($WANIPAddress)&subnet=24&blockgons=true" -Method PUT

I think that I am all set now.  Thanks again for your help and support!
