### ISSUE TITLE
Rest api calls are not working via virtual ip when LAN Network Interface is selected

### ISSUE THREAD

**Issue by abhishekghiya** [jaredhendrickson13/pfsense-api#96]
After selecting the LAN Network interface as shown in snapshot below, the rest api calls are not working via virtual LAN ip

We have made active lan ip as xx.xx.xx.2
standby lan ip as xx.xx.xx.3
virtual lan ip as xx.xx.xx.1

Rest api calls like status system and others are working as expected from active lan and passive lan ips as below:

Active host : http://xx.xx.xx.2:26443/api/v1/status/system
Passive Host : http://xx.xx.xx.3:26443/api/v1/status/system

But it is not working when tried using vlan ip:
Using Vlan : http://xx.xx.xx.1:26443/api/v1/status/system

![image](https://user-images.githubusercontent.com/76930832/110414014-0ec29080-80b5-11eb-9a3b-bd73bdd29e87.png)

When we select Network Interface as any in above snapshot then via vlan ip also it is working as expected.

**Comment by jaredhendrickson13** [comment]
Hey!

Thanks for bringing this up. Looking at the code, this looks to be expected behavior at the moment. It does not take virtual IPs associated with the interface into account. This should be a relatively easy feature to implement. v1.2.0 is ~90% finished, but I should be able to squeeze this one into that release. In the meantime, setting the allowed interfaces to `any` should allow requests on virtual IPs. Once I have a PR containing this feature, I'll update this issue. 

Thanks!
